default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 50013

development:
  <<: *default
  database: bhn9uwsboohx0anxxoap
  password: RjNrk3MsjKfpJ0R8Wdfcnuxt0nKvMw
  username: ubz1ly4u3jq8fgm31heh
  host: bhn9uwsboohx0anxxoap-postgresql.services.clever-cloud.com

test:
  <<: *default
  database: event_system_test

production:
  <<: *default
  database: bhn9uwsboohx0anxxoap
  username: ubz1ly4u3jq8fgm31heh
  password: RjNrk3MsjKfpJ0R8Wdfcnuxt0nKvMw